# Generated by Django 5.0.6 on 2024-06-27 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyHocPhan',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MaLopHocPhan', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('GioHoc', models.CharField(max_length=100)),
                ('PhongHoc', models.CharField(max_length=100)),
                ('SoLuongToiDa', models.IntegerField()),
                ('Status', models.BooleanField(default=False)),
                ('Loai', models.CharField(max_length=20)),
                ('MaGiangVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.giangvien')),
                ('MaLopLyThuyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dangkyhoc.dangkyhocphan')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KetQuaDangKy',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NamHoc', models.CharField(max_length=10)),
                ('HocKy', models.IntegerField()),
                ('MaLopHocPhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dangkyhoc.dangkyhocphan')),
                ('MaSinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sinhvien')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MaMon', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('TenMon', models.CharField(max_length=100)),
                ('SoTinChi', models.IntegerField()),
                ('SoTietLyThuyet', models.IntegerField()),
                ('SoTietThucHanh', models.IntegerField()),
                ('Status', models.CharField(default='Chưa học', max_length=20)),
                ('HeSo', models.FloatField()),
                ('MaKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.khoa')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DieuKienTienQuyet',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('MaMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mon_chinh', to='dangkyhoc.monhoc')),
                ('MaMonTienQuyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_tien_quyet', to='dangkyhoc.monhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dangkyhocphan',
            name='MaMon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dangkyhoc.monhoc'),
        ),
    ]
