# Generated by Django 5.0.6 on 2024-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangkyhoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dangkyhocphan',
            options={'verbose_name': 'Đăng ký học phần', 'verbose_name_plural': 'Đăng ký học phần'},
        ),
        migrations.AlterModelOptions(
            name='dieukientienquyet',
            options={'verbose_name': 'Điều kiện tiên quyết', 'verbose_name_plural': 'Điều kiện tiên quyết'},
        ),
        migrations.AlterModelOptions(
            name='ketquadangky',
            options={'verbose_name': 'Kết quả đăng ký', 'verbose_name_plural': 'Kết quả đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='monhoc',
            options={'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
    ]
