# Generated by Django 5.0.6 on 2024-06-28 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('dangkyhoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KetQuaHocTap',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DiemQuaTrinh', models.FloatField(blank=True, null=True)),
                ('DiemThi', models.FloatField(blank=True, null=True)),
                ('DiemTongKet', models.FloatField(blank=True, null=True)),
                ('DiemChu', models.CharField(blank=True, max_length=100, null=True)),
                ('HocKy', models.IntegerField(blank=True, null=True)),
                ('NamHoc', models.CharField(blank=True, max_length=10, null=True)),
                ('DiemKN1', models.FloatField(blank=True, null=True)),
                ('DiemKN2', models.FloatField(blank=True, null=True)),
                ('DiemKN3', models.FloatField(blank=True, null=True)),
                ('DiemKN4', models.FloatField(blank=True, null=True)),
                ('TongKetKN1', models.FloatField(blank=True, null=True)),
                ('TongKetKN2', models.FloatField(blank=True, null=True)),
                ('TongKetKN3', models.FloatField(blank=True, null=True)),
                ('TongKetKN4', models.FloatField(blank=True, null=True)),
                ('Status', models.CharField(default='Chưa qua', max_length=20)),
                ('MaMon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dangkyhoc.monhoc')),
                ('MaSinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sinhvien')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
