# Generated by Django 5.0.6 on 2024-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ketquahoctap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ketquahoctap',
            options={'verbose_name': 'Kết quả học tập', 'verbose_name_plural': 'Kết quả học tập'},
        ),
    ]
