# Generated by Django 5.0.6 on 2024-07-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketquahoctap', '0002_alter_ketquahoctap_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoDiemQuaTrinh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoKN1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoKN2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoKN3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoKN4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
