# Generated by Django 5.0.6 on 2024-07-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketquahoctap', '0003_ketquahoctap_hesodiemquatrinh_ketquahoctap_hesokn1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquahoctap',
            name='DiemThiLai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoTongKet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
