# Generated by Django 5.0.6 on 2024-07-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangkyhoc', '0002_alter_dangkyhocphan_options_and_more'),
        ('ketquahoctap', '0005_ketquahoctap_diemthilai1_ketquahoctap_diemthilai2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoDiemQuaTrinh',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoKN1',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoKN2',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoKN3',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoKN4',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoTongKet',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN1',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN2',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN3',
        ),
        migrations.RemoveField(
            model_name='ketquahoctap',
            name='HeSoTongKetKN4',
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemKN1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemKN2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemKN3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemKN4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemThiLai1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemThiLai2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemThiLai3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='DiemThiLai4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='TongKetKN1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='TongKetKN2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='TongKetKN3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ketquahoctap',
            name='TongKetKN4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='HeSoMonHoc',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HeSoDiemQuaTrinh', models.FloatField()),
                ('HeSoKN1', models.FloatField()),
                ('HeSoKN2', models.FloatField()),
                ('HeSoKN3', models.FloatField()),
                ('HeSoKN4', models.FloatField()),
                ('HeSoTongKetKN1', models.FloatField()),
                ('HeSoTongKetKN2', models.FloatField()),
                ('HeSoTongKetKN3', models.FloatField()),
                ('HeSoTongKetKN4', models.FloatField()),
                ('HeSoTongKet', models.FloatField()),
                ('HeSoDiemThiLai', models.FloatField()),
                ('MaMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dangkyhoc.monhoc')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hệ số môn học',
                'verbose_name_plural': 'Hệ số môn học',
            },
        ),
    ]
