# Generated by Django 5.0.6 on 2024-07-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ketquahoctap', '0006_remove_ketquahoctap_hesodiemquatrinh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesomonhoc',
            name='HeSoDiemThiLai',
        ),
    ]
