# Generated by Django 5.0.6 on 2024-06-29 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.AddField(
            model_name='giangvien',
            name='Avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='GioiTinh',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giangvien',
            name='Role',
            field=models.CharField(default='Giảng viên', max_length=50),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='Avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='Role',
            field=models.CharField(default='Sinh viên', max_length=50),
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MaTB', models.CharField(max_length=50, unique=True)),
                ('TieuDe', models.CharField(max_length=100)),
                ('NoiDung', models.TextField()),
                ('NgayDang', models.DateTimeField(auto_now_add=True)),
                ('LoaiTB', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('MaGV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.giangvien')),
                ('MaLop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lop')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
