# Generated by Django 5.0.6 on 2024-07-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_useraccount_avatar_giangvien_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giangvien',
            options={'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Giảng viên'},
        ),
        migrations.AlterModelOptions(
            name='khoa',
            options={'verbose_name': 'Khoa', 'verbose_name_plural': 'Khoa'},
        ),
        migrations.AlterModelOptions(
            name='lop',
            options={'verbose_name': 'Lớp', 'verbose_name_plural': 'Lớp'},
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'verbose_name': 'Sinh viên', 'verbose_name_plural': 'Sinh viên'},
        ),
        migrations.AlterModelOptions(
            name='thongbao',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
    ]
